-- Document templates: editable HTML templates for PDF generation
CREATE TABLE IF NOT EXISTS document_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_key VARCHAR(50) NOT NULL UNIQUE,
  label VARCHAR(200) NOT NULL,
  html_content MEDIUMTEXT NOT NULL,
  placeholders JSON NOT NULL DEFAULT ('[]'),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Seed from existing PHP templates
-- NOTE: spaces between signature underscores use Unicode NBSP (U+00A0) instead of &nbsp; to avoid semicolons that break the migration runner's statement splitter.

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('behandlungsvertrag', 'Behandlungsvertrag', '<p><strong>Zwischen:</strong></p>\n<p>{{therapist_name}} (nachfolgend „Therapeutin")</p>\n<p><strong>und</strong></p>\n<p>{{client_name}} (nachfolgend „Klient/in")</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Gegenstand des Vertrages</h2>\n<p>[PLATZHALTER: Hier wird der Gegenstand des Behandlungsvertrages beschrieben. Bitte durch die tatsächlichen Vertragsbedingungen ersetzen.]</p>\n<br>\n<h2>§ 2 Leistungen</h2>\n<p>[PLATZHALTER: Beschreibung der therapeutischen Leistungen, Sitzungsdauer, Häufigkeit.]</p>\n<br>\n<h2>§ 3 Vergütung</h2>\n<p>[PLATZHALTER: Honorar, Zahlungsbedingungen, Absageregelungen.]</p>\n<br>\n<h2>§ 4 Schweigepflicht</h2>\n<p>[PLATZHALTER: Hinweis auf die gesetzliche Schweigepflicht.]</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('datenschutzinfo', 'Datenschutzinformation nach Art. 13 DSGVO', '<p>Sehr geehrte/r {{client_name}},</p>\n<br>\n<p>gemäß Art. 13 der Datenschutz-Grundverordnung (DSGVO) informiere ich Sie über die Verarbeitung Ihrer personenbezogenen Daten:</p>\n<br>\n<h2>1. Verantwortliche Stelle</h2>\n<p>[PLATZHALTER: Name, Adresse, Kontaktdaten der Therapeutin.]</p>\n<br>\n<h2>2. Zweck der Datenverarbeitung</h2>\n<p>[PLATZHALTER: Durchführung der psychotherapeutischen Behandlung, Abrechnung, gesetzliche Aufbewahrungspflichten.]</p>\n<br>\n<h2>3. Rechtsgrundlage</h2>\n<p>[PLATZHALTER: Art. 6 Abs. 1 lit. b DSGVO (Vertrag), Art. 9 Abs. 2 lit. h DSGVO (Gesundheitsdaten).]</p>\n<br>\n<h2>4. Empfänger der Daten</h2>\n<p>[PLATZHALTER: Grundsätzlich keine Weitergabe ohne Einwilligung, Ausnahmen bei gesetzlicher Pflicht.]</p>\n<br>\n<h2>5. Speicherdauer</h2>\n<p>[PLATZHALTER: 10 Jahre nach Abschluss der Behandlung gemäß § 630f BGB.]</p>\n<br>\n<h2>6. Ihre Rechte</h2>\n<p>[PLATZHALTER: Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch, Beschwerde bei Aufsichtsbehörde.]</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('schweigepflichtentbindung', 'Schweigepflichtentbindung', '<p>Ich, <strong>{{client_name}}</strong>, entbinde hiermit</p>\n<p><strong>{{therapist_name}}</strong></p>\n<p>von der Schweigepflicht gegenüber folgenden Personen/Institutionen:</p>\n<br>\n<p>[PLATZHALTER: Hier können spezifische Personen oder Institutionen benannt werden, z.B. Hausarzt, Psychiater, Krankenkasse.]</p>\n<br>\n<p>Diese Entbindung bezieht sich auf:</p>\n<p>[PLATZHALTER: Art der Informationen, die weitergegeben werden dürfen.]</p>\n<br>\n<p>Diese Erklärung kann jederzeit widerrufen werden.</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br><br>\n<p>_________________________</p>\n<p>Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('onlinetherapie', 'Vereinbarung über Online-Therapie', '<p><strong>Zwischen:</strong></p>\n<p>{{therapist_name}} (nachfolgend „Therapeutin")</p>\n<p><strong>und</strong></p>\n<p>{{client_name}} (nachfolgend „Klient/in")</p>\n<br>\n<h2>§ 1 Gegenstand</h2>\n<p>[PLATZHALTER: Vereinbarung über die Durchführung der Therapie über eine Online-Plattform (Videotelefonie).]</p>\n<br>\n<h2>§ 2 Technische Voraussetzungen</h2>\n<p>[PLATZHALTER: Stabile Internetverbindung, ruhiger Raum, Kamera und Mikrofon, unterstützte Plattform.]</p>\n<br>\n<h2>§ 3 Datenschutz und Verschlüsselung</h2>\n<p>[PLATZHALTER: Verwendete Plattform, Ende-zu-Ende-Verschlüsselung, keine Aufzeichnung der Sitzungen.]</p>\n<br>\n<h2>§ 4 Grenzen der Online-Therapie</h2>\n<p>[PLATZHALTER: Hinweis auf Situationen, in denen Präsenztherapie empfohlen wird (akute Krisen, Suizidalität).]</p>\n<br>\n<h2>§ 5 Haftung</h2>\n<p>[PLATZHALTER: Haftungsausschluss bei technischen Störungen.]</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('kurzvertrag', 'Kurzvertrag / Honorarvereinbarung', '<p><strong>Zwischen:</strong></p>\n<p>{{therapist_name}} (nachfolgend „Therapeutin")</p>\n<p><strong>und</strong></p>\n<p>{{client_name}} (nachfolgend „Klient/in")</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Gegenstand</h2>\n<p>Gegenstand dieses Kurzvertrages ist die Durchführung eines Erstgesprächs (Kennenlerngespräch) im Rahmen der psychotherapeutischen Beratung per Videokonferenz.</p>\n<br>\n<h2>§ 2 Umfang und Dauer</h2>\n<p>Das Erstgespräch umfasst eine Sitzung von 50 Minuten Dauer. Es dient dem gegenseitigen Kennenlernen, der Klärung des Anliegens und der Einschätzung, ob und welche therapeutische Begleitung geeignet ist.</p>\n<br>\n<h2>§ 3 Honorar</h2>\n<p>Das Honorar für das Erstgespräch beträgt <strong>95,00 €</strong>. Die Zahlung erfolgt im Voraus per Überweisung oder PayPal. Eine Rechnung wird nach der Sitzung zugestellt.</p>\n<br>\n<h2>§ 4 Absageregelung</h2>\n<p>Eine kostenfreie Absage ist bis 24 Stunden vor dem vereinbarten Termin möglich. Bei späterer Absage oder Nichterscheinen wird das volle Honorar berechnet.</p>\n<br>\n<h2>§ 5 Schweigepflicht</h2>\n<p>Die Therapeutin unterliegt der gesetzlichen Schweigepflicht gemäß § 203 StGB. Alle im Erstgespräch besprochenen Inhalte werden vertraulich behandelt.</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('video_einverstaendnis', 'Einverständnis zur Video-Therapie', '<p><strong>Klient/in:</strong> {{client_name}}</p>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Gegenstand</h2>\n<p>Die therapeutischen Sitzungen werden per Videokonferenz über eine verschlüsselte Plattform durchgeführt. Hiermit erkläre ich mein Einverständnis zur Nutzung dieses Formats.</p>\n<br>\n<h2>§ 2 Technische Voraussetzungen</h2>\n<p>Ich stelle sicher, dass ich über eine stabile Internetverbindung, ein geeignetes Endgerät mit Kamera und Mikrofon sowie einen ruhigen, ungestörten Raum verfüge.</p>\n<br>\n<h2>§ 3 Datenschutz und Vertraulichkeit</h2>\n<p>Ich bin darauf hingewiesen worden, dass bei der Nutzung digitaler Kommunikationsmittel trotz Verschlüsselung ein Restrisiko bezüglich der Datensicherheit besteht. Ich akzeptiere dieses Risiko.</p>\n<br>\n<h2>§ 4 Aufzeichnungsverbot</h2>\n<p>Jegliche Aufzeichnung (Bild, Ton, Screenshot) der Sitzung ist ohne ausdrückliche schriftliche Zustimmung beider Parteien untersagt.</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('datenschutz_digital', 'Datenschutzrisiken digitaler Kommunikation', '<p><strong>Klient/in:</strong> {{client_name}}</p>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Hinweis auf Datenschutzrisiken</h2>\n<p>Im Rahmen unserer Zusammenarbeit kann Kommunikation über digitale Kanäle stattfinden (E-Mail, Videokonferenz, Messenger). Ich wurde darüber aufgeklärt, dass diese Kommunikationsformen trotz Verschlüsselung mit folgenden Risiken verbunden sein können:</p>\n<br>\n<ul>\n<li>Unbefugter Zugriff auf Kommunikationsinhalte durch Dritte</li>\n<li>Datenverlust oder technische Störungen</li>\n<li>Serverstandorte außerhalb der EU</li>\n<li>Metadatenerhebung durch Plattformanbieter</li>\n</ul>\n<br>\n<h2>§ 2 Verantwortlichkeit</h2>\n<p>Die Therapeutin trifft geeignete Maßnahmen zum Schutz der Kommunikation (z.B. Ende-zu-Ende-Verschlüsselung, sichere Plattformen). Ein vollständiger Schutz kann jedoch technisch nicht garantiert werden.</p>\n<br>\n<h2>§ 3 Einverständnis</h2>\n<p>Ich habe die oben genannten Risiken zur Kenntnis genommen und bin mit der Nutzung digitaler Kommunikationskanäle im Rahmen der therapeutischen Zusammenarbeit einverstanden.</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('email_einwilligung', 'Einwilligung zur E-Mail-Kommunikation', '<p><strong>Klient/in:</strong> {{client_name}}</p>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>Einwilligung zur E-Mail-Kommunikation</h2>\n<p>Hiermit erkläre ich mein Einverständnis, dass {{therapist_name}} mich im Rahmen der therapeutischen Zusammenarbeit per E-Mail kontaktieren darf.</p>\n<br>\n<p>Dies umfasst insbesondere:</p>\n<ul>\n<li>Terminbestätigungen und -erinnerungen</li>\n<li>Versand von Dokumenten und Rechnungen</li>\n<li>Organisatorische Absprachen</li>\n</ul>\n<br>\n<p><strong>Hinweis:</strong> E-Mail-Kommunikation ist nicht vollständig vor dem Zugriff Dritter geschützt. Therapeutische Inhalte werden nach Möglichkeit nicht per E-Mail übermittelt. Für vertrauliche Kommunikation stehen sichere Alternativen zur Verfügung.</p>\n<br>\n<p>Diese Einwilligung kann jederzeit widerrufen werden.</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('rechnung', 'Rechnung', '<p><strong>Rechnungsempfänger:</strong> {{client_name}}</p>\n<p><strong>Rechnungsnummer:</strong> {{invoice_number}}</p>\n<p><strong>Rechnungsdatum:</strong> {{date}}</p>\n<br>\n<h2>Leistungsübersicht</h2>\n<br>\n<table border="1" cellpadding="6">\n<tr>\n<td width="50%"><strong>Leistung</strong></td>\n<td width="20%"><strong>Datum</strong></td>\n<td width="15%"><strong>Dauer</strong></td>\n<td width="15%" align="right"><strong>Betrag</strong></td>\n</tr>\n<tr>\n<td>{{therapy_label}}</td>\n<td>{{session_date}} {{session_time}}</td>\n<td>{{duration_minutes}} Min.</td>\n<td align="right">{{amount}}</td>\n</tr>\n<tr>\n<td colspan="3" align="right"><strong>Gesamtbetrag:</strong></td>\n<td align="right"><strong>{{amount}}</strong></td>\n</tr>\n</table>\n<br>\n<p><strong>Hinweis:</strong> Gemäß § 4 Nr. 14 UStG ist die Leistung umsatzsteuerbefreit (Heilbehandlung im Bereich der Humanmedizin).</p>\n<br>\n<p>Bitte überweisen Sie den Betrag innerhalb von 14 Tagen.</p>\n<br><br>\n<p>Mit freundlichen Grüßen</p>\n<p>{{therapist_name}}</p>', '["client_name", "therapist_name", "date", "invoice_number", "amount", "duration_minutes", "therapy_label", "session_date", "session_time"]');
