-- Split behandlungsvertrag into three context-specific contract templates

DELETE FROM document_templates WHERE template_key = 'behandlungsvertrag';

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('vertrag_erstgespraech', 'Vertrag — Erstgespräch', '<h1>Vertrag — Erstgespräch</h1>\n<p><strong>Zwischen:</strong></p>\n<p>{{therapist_name}} (nachfolgend „Therapeutin")</p>\n<p><strong>und</strong></p>\n<p>{{client_name}} (nachfolgend „Klient/in")</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Gegenstand des Vertrages</h2>\n<p>[PLATZHALTER: Hier wird der Gegenstand des Vertrages für das Erstgespräch beschrieben.]</p>\n<br>\n<h2>§ 2 Leistungen</h2>\n<p>[PLATZHALTER: Beschreibung des Erstgesprächs, Dauer, Ablauf.]</p>\n<br>\n<h2>§ 3 Vergütung</h2>\n<p>[PLATZHALTER: Honorar, Zahlungsbedingungen, Absageregelungen.]</p>\n<br>\n<h2>§ 4 Schweigepflicht</h2>\n<p>[PLATZHALTER: Hinweis auf die gesetzliche Schweigepflicht.]</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('vertrag_einzeltherapie', 'Vertrag — Einzeltherapie', '<h1>Vertrag — Einzeltherapie</h1>\n<p><strong>Zwischen:</strong></p>\n<p>{{therapist_name}} (nachfolgend „Therapeutin")</p>\n<p><strong>und</strong></p>\n<p>{{client_name}} (nachfolgend „Klient/in")</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Gegenstand des Vertrages</h2>\n<p>[PLATZHALTER: Hier wird der Gegenstand des Behandlungsvertrages für Einzeltherapie beschrieben.]</p>\n<br>\n<h2>§ 2 Leistungen</h2>\n<p>[PLATZHALTER: Beschreibung der therapeutischen Leistungen, Sitzungsdauer, Häufigkeit.]</p>\n<br>\n<h2>§ 3 Vergütung</h2>\n<p>[PLATZHALTER: Honorar, Zahlungsbedingungen, Absageregelungen.]</p>\n<br>\n<h2>§ 4 Schweigepflicht</h2>\n<p>[PLATZHALTER: Hinweis auf die gesetzliche Schweigepflicht.]</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');

INSERT INTO document_templates (template_key, label, html_content, placeholders) VALUES ('vertrag_gruppentherapie', 'Vertrag — Gruppentherapie', '<h1>Vertrag — Gruppentherapie</h1>\n<p><strong>Zwischen:</strong></p>\n<p>{{therapist_name}} (nachfolgend „Therapeutin")</p>\n<p><strong>und</strong></p>\n<p>{{client_name}} (nachfolgend „Klient/in")</p>\n<br>\n<p><strong>Datum:</strong> {{date}}</p>\n<br>\n<h2>§ 1 Gegenstand des Vertrages</h2>\n<p>[PLATZHALTER: Hier wird der Gegenstand des Behandlungsvertrages für Gruppentherapie beschrieben.]</p>\n<br>\n<h2>§ 2 Leistungen</h2>\n<p>[PLATZHALTER: Beschreibung der Gruppentherapie, Sitzungsdauer, Häufigkeit, Gruppengröße.]</p>\n<br>\n<h2>§ 3 Vergütung</h2>\n<p>[PLATZHALTER: Honorar, Zahlungsbedingungen, Absageregelungen.]</p>\n<br>\n<h2>§ 4 Schweigepflicht</h2>\n<p>[PLATZHALTER: Hinweis auf die gesetzliche Schweigepflicht.]</p>\n<br>\n<h2>§ 5 Vertraulichkeit in der Gruppe</h2>\n<p>[PLATZHALTER: Besondere Vertraulichkeitsvereinbarung für das Gruppenformat.]</p>\n<br><br>\n<p>_________________________        _________________________</p>\n<p>Ort, Datum                                Unterschrift Klient/in</p>', '["client_name", "therapist_name", "date"]');
