ALTER TABLE clients ADD COLUMN street VARCHAR(255) DEFAULT NULL AFTER phone;
ALTER TABLE clients ADD COLUMN zip VARCHAR(10) DEFAULT NULL AFTER street;
ALTER TABLE clients ADD COLUMN city VARCHAR(100) DEFAULT NULL AFTER zip;
ALTER TABLE clients ADD COLUMN country VARCHAR(100) DEFAULT 'Deutschland' AFTER city;
