CREATE TABLE blocked_days (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  block_date DATE NOT NULL UNIQUE,
  reason     VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
